// Copyright 2017-2021 @encointer/util authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@encointer/util', version: '0.4.0' };
