export default {
  rpc: {},
  types: {
    IntegriteePublicGetter: {
      _enum: {
        some_value: null,
        total_issuance: null,
        undistributed_fees: 'Option<IntegriteeAssetId>',
        unused_index_3: null,
        unused_index_4: null,
        unused_index_5: null,
        unused_index_6: null,
        unused_index_7: null,
        unused_index_8: null,
        unused_index_9: null,
        parentchains_info: null,
        note_buckets_info: null,
        shard_info: null,
        unused_index_13: null,
        unused_index_14: null,
        unused_index_15: null,
        unused_index_16: null,
        unused_index_17: null,
        unused_index_18: null,
        unused_index_19: null,
        unused_index_20: null,
        unused_index_21: null,
        unused_index_22: null,
        unused_index_23: null,
        unused_index_24: null,
        unused_index_25: null,
        unused_index_26: null,
        unused_index_27: null,
        unused_index_28: null,
        unused_index_29: null,
        unused_index_30: null,
        unused_index_31: null,
        unused_index_32: null,
        unused_index_33: null,
        unused_index_34: null,
        unused_index_35: null,
        unused_index_36: null,
        unused_index_37: null,
        unused_index_38: null,
        unused_index_39: null,
        asset_total_issuance: 'IntegriteeAssetId',
        unused_index_41: null,
        unused_index_42: null,
        unused_index_43: null,
        unused_index_44: null,
        unused_index_45: null,
        unused_index_46: null,
        unused_index_47: null,
        unused_index_48: null,
        unused_index_49: null,
        guess_the_number: 'GuessTheNumberPublicGetter',
        credits: 'CreditsTrustedGetter',
      }
    },
    IntegriteeTrustedGetter: {
      _enum: {
        account_info: 'AccountId',
        account_info_and_session_proxies: 'AccountId',
        account_essentials: 'AccountId',
        unused_index_3: null,
        unused_index_4: null,
        unused_index_5: null,
        unused_index_6: null,
        unused_index_7: null,
        unused_index_8: null,
        unused_index_9: null,
        notes_for: 'NotesForArgs',
        unused_index_11: null,
        unused_index_12: null,
        unused_index_13: null,
        unused_index_14: null,
        unused_index_15: null,
        unused_index_16: null,
        unused_index_17: null,
        unused_index_18: null,
        unused_index_19: null,
        unused_index_20: null,
        unused_index_21: null,
        unused_index_22: null,
        unused_index_23: null,
        unused_index_24: null,
        unused_index_25: null,
        unused_index_26: null,
        unused_index_27: null,
        unused_index_28: null,
        unused_index_29: null,
        unused_index_30: null,
        unused_index_31: null,
        unused_index_32: null,
        unused_index_33: null,
        unused_index_34: null,
        unused_index_35: null,
        unused_index_36: null,
        unused_index_37: null,
        unused_index_38: null,
        unused_index_39: null,
        asset_balance: 'AssetBalanceArgs',
        unused_index_41: null,
        unused_index_42: null,
        unused_index_43: null,
        unused_index_44: null,
        unused_index_45: null,
        unused_index_46: null,
        unused_index_47: null,
        unused_index_48: null,
        unused_index_49: null,
        guess_the_number: 'GuessTheNumberTrustedGetter',
        credits: 'CreditsTrustedGetter',
      }
    },
    IntegriteeTrustedGetterSigned: {
      getter: 'IntegriteeTrustedGetter',
      delegate: 'Option<AccountId>',
      signature: 'MultiSignature'
    },
    IntegriteeGetter: {
      _enum: {
        public: 'IntegriteePublicGetter',
        trusted: 'IntegriteeTrustedGetterSigned'
      }
    },
    IntegriteeTrustedOperation: {
      _enum: {
        indirect_call: 'IntegriteeTrustedCallSigned',
        direct_call: 'IntegriteeTrustedCallSigned',
        get: 'IntegriteeGetter'
      }
    },
    IntegriteeTrustedCallSigned: {
      call: 'IntegriteeTrustedCall',
      nonce: 'u32',
      delegate: 'Option<AccountId>',
      signature: 'MultiSignature'
    },
    IntegriteeTrustedCall: {
      _enum: {
        noop: 'AccountId',
        timestamp_set: 'TimestampSetArgs',
        balance_transfer: 'BalanceTransferArgs',
        balance_unshield: 'BalanceUnshieldArgs',
        balance_shield: 'BalanceShieldArgs',
        balance_transfer_with_note: 'BalanceTransferWithNoteArgs',
        balance_shield_through_enclave_bridge_pallet: 'BalanceShieldThroughEnclaveBridgePalletArgs',
        balance_unshield_through_enclave_bridge_pallet: 'BalanceUnshieldThroughEnclaveBridgePalletArgs',
        unused_index_8: null,
        unused_index_9: null,
        unused_index_10: null,
        unused_index_11: null,
        unused_index_12: null,
        unused_index_13: null,
        unused_index_14: null,
        unused_index_15: null,
        unused_index_16: null,
        unused_index_17: null,
        unused_index_18: null,
        unused_index_19: null,
        send_note: 'SendNoteArgs',
        send_relayed_note: 'SendRelayedNoteArgs',
        send_relayed_note_stripped: 'SendRelayedNoteStrippedArgs',
        unused_index_23: null,
        unused_index_24: null,
        unused_index_25: null,
        unused_index_26: null,
        unused_index_27: null,
        unused_index_28: null,
        unused_index_29: null,
        add_session_proxy: 'AddSessionProxyArgs',
        unused_index_31: null,
        unused_index_32: null,
        unused_index_33: null,
        unused_index_34: null,
        unused_index_35: null,
        unused_index_36: null,
        unused_index_37: null,
        unused_index_38: null,
        unused_index_39: null,
        unused_index_40: null,
        unused_index_41: null,
        assets_transfer: 'AssetsTransferArgs',
        assets_unshield: 'AssetsUnshieldArgs',
        assets_shield: 'AssetsShieldArgs',
        assets_transfer_with_note: 'AssetsTransferWithNoteArgs',
        unused_index_46: null,
        unused_index_47: null,
        unused_index_48: null,
        unused_index_49: null,
        guess_the_number: 'GuessTheNumberTrustedCall',
        credits: 'CreditsTrustedCall'
      }
    },
    TimestampSetArgs: '(AccountId, H160, BalanceType)',
    AssetsTransferArgs: '(AccountId, AccountId, IntegriteeAssetId, BalanceType)',
    AssetsUnshieldArgs: '(AccountId, AccountId, IntegriteeAssetId, BalanceType, ShardIdentifier)',
    AssetsShieldArgs: '(AccountId, AccountId, IntegriteeAssetId, BalanceType, ParentchainId)',
    AssetsTransferWithNoteArgs: '(AccountId, AccountId, IntegriteeAssetId, BalanceType, String)',
    BalanceTransferArgs: '(AccountId, AccountId, BalanceType)',
    BalanceTransferWithNoteArgs: '(AccountId, AccountId, BalanceType, String)',
    BalanceShieldThroughEnclaveBridgePalletArgs: '(AccountId, AccountId, BalanceType)',
    BalanceUnshieldThroughEnclaveBridgePalletArgs: '(AccountId, AccountId, BalanceType, ShardIdentifier)',
    BalanceShieldArgs: '(AccountId, AccountId, BalanceType, ParentchainId)',
    BalanceUnshieldArgs: '(AccountId, AccountId, BalanceType, ShardIdentifier)',
    NotesForArgs: '(AccountId, BucketIndex)',
    BucketIndex: 'u32',
    NoteIndex: 'u64',
    TimestampedTrustedNote: {
      timestamp: 'Moment',
      version: 'u16',
      note: 'TrustedNote'
    },
    TrustedNote: {
      _enum: {
        SuccessfulTrustedCall: 'Vec<u8>',
        SgxRuntimeEvent: 'Vec<u8>',
        String: 'Text'
      }
    },
    BucketInfo: {
      index: 'BucketIndex',
      bytes: 'u32',
      begins_at: 'Moment',
      ends_at: 'Moment',
    },
    NotesBucketInfo: {
      first: 'Option<BucketInfo>',
      last: 'Option<BucketInfo>',
    },
    GuessTheNumberPublicGetter: {
      _enum: {
        guess_the_number_info: null,
      }
    },
    GuessTheNumberTrustedGetter: {
      _enum: {
        attempts: 'AttemptsArg'
      }
    },
    CreditsTrustedGetter: {
      _enum: {
        credits: 'CreditsArg',
        credit_class_info: 'CreditClassInfoArg'
      }
    },
    CreditsArg: {
      origin: 'AccountId',
      class_id: 'CreditClassId'
    },
    CreditClassInfoArg: 'CreditsArg',
    AssetBalanceArgs: '(AccountId, IntegriteeAssetId)',
    AttemptsArg: {
      origin: 'AccountId'
    },
    SessionProxyRole: {
      _enum: {
        readBalance: null,
        readAny: null,
        nonTransfer: null,
        any: null,
        transferAllowance: 'Balance'
      }
    },
    SessionProxyCredentials: {
      role: 'SessionProxyRole',
      expiry: 'Option<Moment>',
      seed: 'H256',
    },
    AddSessionProxyArgs: '(AccountId, AccountId, SessionProxyCredentials)',
    AccountInfoAndSessionProxies: {
      account_info: 'AccountInfo',
      session_proxies: 'Vec<SessionProxyCredentials>'
    },
    AccountEssentials: {
      account_info: 'AccountInfo',
      session_proxies: 'Vec<SessionProxyCredentials>',
      asset_balances: 'Vec<IntegriteeAssetBalance>',
    },
    IntegriteeAssetBalance: {
      asset_id: 'IntegriteeAssetId',
      balance: 'Balance',
    },
    SendNoteArgs: '(AccountId, AccountId, String)',
    SendRelayedNoteArgs: '(AccountId, AccountId, ConversationId, RelayedNoteRequest)',
    SendRelayedNoteStrippedArgs: '(AccountId, AccountId, ConversationId, RelayedNoteRetrievalInfo)',
    ConversationId: 'u32',
    NoteRelayType: {
      _enum: {
        Here: null,
        Ipfs: null,
        Undeclared: null,
      }
    },
    RelayedNoteRequest: {
      allow_onchain_fallback: 'bool',
      note_relay_type: 'NoteRelayType',
      msg: 'Text',
      maybe_encryption_key: 'Option<H256>',
    },
    RelayedNoteRetrievalInfo: {
      _enum: {
        Here: 'RelayedNoteRetrievalHere',
        Ipfs: 'RelayedNoteRetrievalIpfs',
        Undeclared: 'RelayedNoteRetrievalUndeclared',
      }
    },
    RelayedNoteRetrievalHere: {
      msg: 'Text',
    },
    RelayedNoteRetrievalIpfs: {
      ipfs_hash: 'Vec<u8>',
      encryption_key: 'H256',
    },
    RelayedNoteRetrievalUndeclared: {
      encryption_key: 'H256',
    },
    GuessTheNumberTrustedCall: {
      _enum: {
        set_winnings: 'GuessTheNumberSetWinningsArgs',
        push_by_one_day: 'AccountId',
        guess: 'GuessArgs',
      }
    },
    GuessType: 'u32',
    GuessTheNumberInfo: {
      account: 'AccountId',
      balance: 'Balance',
      winnings: 'Balance',
      next_round_timestamp: 'Moment',
      last_winners: 'Vec<AccountId>',
      maybe_last_lucky_number: 'Option<GuessType>',
      maybe_last_winning_distance: 'Option<GuessType>',
    },
    GuessTheNumberSetWinningsArgs: '(AccountId, Balance)',
    GuessArgs: '(AccountId, GuessType)',
    CreditClassId: 'u32',
    CreditsTrustedCall: {
      _enum: {
        create_class: 'CreditsCreateClassArgs',
        destroy_class: 'CreditsDestroyClassArgs',
        claim: 'CreditsClaimArgs',
        mint: 'CreditsMintArgs',
        redeem: 'CreditsRedeemArgs',
      }
    },
    CreditsCreateClassArgs: '(AccountId, CreditClassId)',
    CreditsDestroyClassArgs: '(AccountId, CreditClassId)',
    CreditsClaimArgs: '(AccountId, CreditClassId, Hash)',
    CreditsMintArgs: '(AccountId, CreditClassId, AccountId, Balance)',
    CreditsRedeemArgs: '(AccountId, CreditClassId, AccountId, Balance)',
    IntegriteeAssetId: {
      _enum: {
        unused_index_0: null,
        unused_index_1: null,
        unused_index_2: null,
        unused_index_3: null,
        unused_index_4: null,
        unused_index_5: null,
        unused_index_6: null,
        unused_index_7: null,
        unused_index_8: null,
        unused_index_9: null,
        USDT: null,
        USDT_E: null,
        unused_index_12: null,
        unused_index_13: null,
        unused_index_14: null,
        unused_index_15: null,
        unused_index_16: null,
        unused_index_17: null,
        unused_index_18: null,
        unused_index_19: null,
        USDC: null,
        USDC_E: null,
        unused_index_22: null,
        EURC_E: null,
        unused_index_24: null,
        unused_index_25: null,
        unused_index_26: null,
        unused_index_27: null,
        unused_index_28: null,
        unused_index_29: null,
        ETH: null,
        WETH: null,
        unused_index_32: null,
        unused_index_33: null,
        unused_index_34: null,
        unused_index_35: null,
        BTC: null,
        WBTC_E: null,
        unused_index_38: null,
        unused_index_39: null,
        PEPE_E: null,
        unused_index_41: null,
      }
    },
  }
}
