// Copyright 2017-2021 @encointer/worker-api authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@encointer/worker-api', version: '0.4.1' };
